[package]
name = "subset"
version = "0.1.0"
edition = "2024"

[dependencies]
subset-derive = { path = "../subset-derive"}

[lib]
proc-macro = false

[dev-dependencies]
chrono = { version = "0.4.42", features = ["serde"]}
